version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: nest-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=cymulate-task
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - app-network
    depends_on:
      - mongodb

  phishing-management:
    build:
      context: ./phishing-management
    container_name: phishing-management
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/cymulate-task?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
      - SIMULATION_API_URL=http://phishing-simulation:5001
      - CORS_ORIGIN=http://frontend:5173,http://localhost:5173,http://phishing-simulation:5001
    depends_on:
      - mongodb
    networks:
      - app-network

  phishing-simulation:
    build:
      context: ./phishing-simulation
    container_name: phishing-simulation
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/cymulate-task?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
      - EMAIL_USER=example@gmail.com
      - EMAIL_PASSWORD=your_email_app_password
      - SERVER_URL=http://localhost:5001
      - CORS_ORIGIN=http://frontend:5173,http://localhost:5173,http://phishing-management:5000
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NEXT_PUBLIC_API_URL=http://phishing-management:5000
    depends_on:
      - phishing-management
      - phishing-simulation
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
